---
ID: "57ac06e1-84e8-4648-bb9d-f7c6ee964e9a"
Parent: "322f2d51-8920-4b5f-97c7-ac154d4a28f7"
Template: "322f2d51-8920-4b5f-97c7-ac154d4a28f7"
Path: /sitecore/templates/Feature/Catalog/Rendering Parameters/Featured Products By Category CTA Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "99eda751-8757-4e32-a40c-b38636edd137"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bsewards@rightpoint.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250513T135400Z
