---
ID: "5e9830cd-00c1-4d36-8028-eeac030c76d5"
Parent: "dfcd2a4a-e2bd-4aa5-8863-f18060fd6dec"
Template: "dfcd2a4a-e2bd-4aa5-8863-f18060fd6dec"
Path: /sitecore/templates/Feature/Catalog/Rendering Parameters/LanguageTester Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8b18f5a3-5e36-45e5-bac9-801ebddf840e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bsewards@rightpoint.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250515T194700Z
