---
ID: "bff85e75-6644-444c-80ac-c7f99d528fca"
Parent: "e6d66c19-2121-4da7-8066-529109aa077c"
Template: "e6d66c19-2121-4da7-8066-529109aa077c"
Path: /sitecore/templates/Project/Catalog/Global Data Folder/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250513T140710Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\bsewards@rightpoint.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\bsewards@rightpoint.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ed558334-f8b1-4e44-b3cb-93e7fd4ef1f7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\bsewards@rightpoint.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250513T140710Z
